// lib/string.dart
import 'package:flutter/material.dart';

class Strings {
  static const Map<String, String> en = {
    'home': 'Home',
    'search': 'Search',
    'account': 'Account',
    'book': 'Book',
    'mapPlaceholder': 'MAP – Google Maps later',

    'bookAppointment': 'Book appointment',
    'vitals': 'Vitals',
    'readFromBracelet': 'Check your eligibility',
    'reading': 'Reading...',
    'pickDateTime': 'Pick date & time',
    'pickDate': 'Pick date',
    'pickTime': 'Pick time',
    'confirm': 'Confirm',
    'pleasePickDateTime': 'Please select date and time',
    'readVitalsFirst': 'Read vitals first',
    'notEligible': 'Not eligible to donate',
    'eligibility_age': 'You must be 18+ to donate',
    'eligibility_hb': 'Hemoglobin too low',
    'eligibility_bp': 'Blood pressure out of range',
    'eligibility_pulse': 'Pulse out of range',
    'shortages': 'Needed',
    'profile': 'Profile',
    'name': 'Name',
    'bloodType': 'Blood type',
    'age': 'Age',
    'noVitals': 'No vitals yet',
    'upcomingAppointments': 'Upcoming appointment(s)',
    'noAppointments': 'No appointments',
    'reschedule': 'Reschedule',
    'cancel': 'Cancel',
    'save': 'Save',
    'units': 'Units',
    'inventoryPanel': 'Inventory panel',
    'editQuantity': 'Edit quantity',
    'refresh': 'Refresh',
    'edit': 'Edit',
    'editProfile': 'Edit profile',
    'profileUpdated': 'Profile updated successfully',
    'existingAppointmentTitle': 'Existing appointment',
    'existingAppointmentMessage': 'You already have an upcoming appointment. Please cancel or reschedule it before booking a new one.',
    'ok': 'OK',
    'donationSite': 'Donation Site',
    'bookedSuccessfully': 'Appointment booked',
    'login': 'Log in',
    'loginSubtitle': 'Choose how you’d like to log in',
    'loginDonor': 'Donor login',
    'loginSite': 'Donation site login',
    'loginDonorSubtitle': 'Sign in as a donor to manage your donations and appointments.',
    'loginSiteSubtitle': 'Sign in with your donation site credentials to manage inventory and bookings.',
    'logInAsDonor': 'Log in as donor',
    'logInAsSite': 'Log in as donation site',
    'orSignUp': 'Or sign up',
    'signUpDonor': 'Sign up as donor',
    'signUpSite': 'Sign up as donation site',
    'noAccountSignUp': 'No account? Sign up',
    'accountNotFound': 'Account not found. Please sign up first.',
    'wrongPassword': 'Incorrect password, try again.',
    'email': 'Email',
    'phoneNumber': 'Phone number',
    'location': 'Location',
    'password': 'Password',
    'loginButton': 'Log in',
    'signUp': 'Sign up',
    'donorRole': 'Donor',
    'donationSiteRole': 'Donation site',
    'invalidEmail': 'Please enter a valid email address.',
    'emailRequired': 'Email is required.',
    'passwordRequired': 'Password is required.',
    'passwordRequirements': 'Password must be at least 8 characters and include a number.',
    'nameRequired': 'Name is required.',
    'siteName': 'Site name',
    'contactNumber': 'Contact number',
    'siteNameRequired': 'Site name is required.',
    'centerRequired': 'Choose a donation center.',
    'emailTaken': 'That email is already registered.',
    'chooseCenter': 'Choose center',
    'logout': 'Log out',
    'loggedOut': 'You have been logged out.',
    'siteCannotBook': 'Donation sites cannot book appointments.',
    'ageRestriction': 'Must be 18 or older to log in.',
    'noShortages': 'All blood types above minimum',
    'centerCentral': 'Central Donation Center',
    'centerNorth': 'North Donation Point',
    'centerSouth': 'South Donation Point',
    'donationSafe': 'You are good to donate today.',
    'donationUnsafe': 'Not eligible to donate today.',
    'donationUnsafeDetails': 'Vitals are outside the safe range. Please contact staff.',
    'braceletErrorNoProfile': 'Complete your profile before reading vitals.',
    'english': 'English',
    'arabic': 'العربية',
    'unknownDonor': 'Unknown donor',
  };

  static const Map<String, String> ar = {
    'home': 'الرئيسية',
    'search': 'بحث',
    'account': 'الحساب',
    'book': 'حجز',
    'mapPlaceholder': 'الخريطة – لاحقًا Google Maps',

    'bookAppointment': 'حجز موعد',
    'vitals': 'العلامات الحيوية',
    'readFromBracelet': 'تحقق من أهليتك',
    'reading': 'جاري القراءة…',
    'pickDateTime': 'اختيار التاريخ والوقت',
    'pickDate': 'اختر التاريخ',
    'pickTime': 'اختر الوقت',
    'confirm': 'تأكيد',
    'pleasePickDateTime': 'الرجاء اختيار التاريخ والوقت',
    'readVitalsFirst': 'اقرأ العلامات الحيوية أولاً',
    'notEligible': 'غير مؤهل للتبرع',
    'eligibility_age': 'يجب أن يكون العمر 18 فأكثر',
    'eligibility_hb': 'الهيموجلوبين منخفض',
    'eligibility_bp': 'ضغط الدم خارج النطاق',
    'eligibility_pulse': 'النبض خارج النطاق',
    'shortages': 'نواقص',
    'profile': 'الملف الشخصي',
    'name': 'الاسم',
    'bloodType': 'فصيلة الدم',
    'age': 'العمر',
    'noVitals': 'لا توجد قراءات حيوية بعد',
    'upcomingAppointments': 'المواعيد القادمة',
    'noAppointments': 'لا توجد مواعيد',
    'reschedule': 'إعادة جدولة',
    'cancel': 'إلغاء',
    'save': 'حفظ',
    'units': 'عدد الأكياس',
    'inventoryPanel': 'لوحة المخزون',
    'editQuantity': 'تعديل الكمية',
    'refresh': 'تحديث',
    'edit': 'تعديل',
    'editProfile': 'تعديل الملف الشخصي',
    'profileUpdated': 'تم تحديث الملف بنجاح',
    'existingAppointmentTitle': 'موعد موجود',
    'existingAppointmentMessage': 'لديك موعد قادم بالفعل. الرجاء إلغاءه أو إعادة جدولته قبل حجز موعد جديد.',
    'ok': 'حسناً',
    'donationSite': 'موقع التبرع',
    'bookedSuccessfully': 'تم حجز الموعد',
    'login': 'تسجيل الدخول',
    'loginSubtitle': 'اختاري طريقة تسجيل الدخول المناسبة لك',
    'loginDonor': 'تسجيل دخول المتبرع',
    'loginSite': 'تسجيل دخول موقع التبرع',
    'loginDonorSubtitle': 'ادخلي كمتبرع لإدارة تبرعاتك ومواعيدك.',
    'loginSiteSubtitle': 'ادخلي بحساب موقع التبرع لإدارة المخزون والمواعيد.',
    'logInAsDonor': 'تسجيل الدخول كمتبرع',
    'logInAsSite': 'تسجيل الدخول كموقع تبرع',
    'orSignUp': 'أو أنشئي حساباً جديداً',
    'signUpDonor': 'إنشاء حساب متبرع',
    'signUpSite': 'إنشاء حساب موقع تبرع',
    'noAccountSignUp': 'ما عندك حساب؟ أنشئي واحداً',
    'accountNotFound': 'ما لقينا حساب بهذا البريد، الرجاء إنشاء حساب جديد.',
    'wrongPassword': 'كلمة المرور غير صحيحة، حاولي مرة ثانية.',
    'email': 'البريد الإلكتروني',
    'phoneNumber': 'رقم الهاتف',
    'location': 'الموقع',
    'password': 'كلمة المرور',
    'loginButton': 'تسجيل الدخول',
    'signUp': 'تسجيل',
    'donorRole': 'متبرع',
    'donationSiteRole': 'موقع تبرع',
    'invalidEmail': 'الرجاء إدخال بريد إلكتروني صحيح.',
    'emailRequired': 'البريد الإلكتروني مطلوب.',
    'passwordRequired': 'كلمة المرور مطلوبة.',
    'passwordRequirements': 'يجب أن تكون كلمة المرور 8 أحرف على الأقل وتتضمن رقماً.',
    'nameRequired': 'الاسم مطلوب.',
    'siteName': 'اسم الموقع',
    'contactNumber': 'رقم التواصل',
    'siteNameRequired': 'اسم الموقع مطلوب.',
    'centerRequired': 'اختاري مركز التبرع.',
    'emailTaken': 'البريد مسجّل مسبقاً.',
    'chooseCenter': 'اختاري المركز',
    'noShortages': 'لا توجد نواقص حالياً',
    'centerCentral': 'مركز التبرع المركزي',
    'centerNorth': 'نقطة التبرع الشمالية',
    'centerSouth': 'نقطة التبرع الجنوبية',
    'logout': 'تسجيل الخروج',
    'loggedOut': 'تم تسجيل خروجك.',
    'siteCannotBook': 'حساب موقع التبرع لا يمكنه حجز المواعيد.',
    'ageRestriction': 'يجب أن يكون عمرك 18 أو أكثر لتسجيل الدخول.',
    'donationSafe': 'جاهز للتبرع اليوم.',
    'donationUnsafe': 'غير مؤهل للتبرع اليوم.',
    'donationUnsafeDetails': 'العلامات الحيوية خارج النطاق الآمن. الرجاء مراجعة الطاقم.',
    'braceletErrorNoProfile': 'أكملي بيانات ملفك قبل قراءة العلامات الحيوية.',
    'english': 'English',
    'arabic': 'العربية',
    'unknownDonor': 'متبرع غير معروف',
  };

  static String t(BuildContext context, String key) {
    final lang = Localizations.localeOf(context).languageCode;
    final map = (lang == 'ar') ? ar : en;
    return map[key] ?? key;
  }

  static TextDirection dir(BuildContext context) {
    final lang = Localizations.localeOf(context).languageCode;
    return (lang == 'ar') ? TextDirection.rtl : TextDirection.ltr;
  }
}
